#include "repositories/Repositories.h"
#include <sqlite3.h>
#include <stdexcept>

InstrumentRepository::InstrumentRepository(Database& db):db_(db){}
int InstrumentRepository::add(const Instrument& i){ sqlite3_stmt* stmt{}; std::string sql="INSERT INTO instruments(symbol,name,type,currency,current_price) VALUES(?,?,?,?,?)"; if(sqlite3_prepare_v2(db_.raw(),sql.c_str(),-1,&stmt,nullptr)!=SQLITE_OK) throw std::runtime_error(sqlite3_errmsg(db_.raw())); sqlite3_bind_text(stmt,1,i.symbol.c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(stmt,2,i.name.c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(stmt,3,i.type.c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(stmt,4,i.currency.c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_double(stmt,5,i.currentPrice); if(sqlite3_step(stmt)!=SQLITE_DONE){std::string e=sqlite3_errmsg(db_.raw()); sqlite3_finalize(stmt); throw std::runtime_error(e);} sqlite3_finalize(stmt); return (int)db_.lastInsertId(); }
std::optional<Instrument> InstrumentRepository::findBySymbol(const std::string& s){ sqlite3_stmt* stmt{}; std::string sql="SELECT id,symbol,name,type,currency,current_price FROM instruments WHERE symbol=?"; if(sqlite3_prepare_v2(db_.raw(),sql.c_str(),-1,&stmt,nullptr)!=SQLITE_OK) throw std::runtime_error(sqlite3_errmsg(db_.raw())); sqlite3_bind_text(stmt,1,s.c_str(),-1,SQLITE_TRANSIENT); if(sqlite3_step(stmt)==SQLITE_ROW){ Instrument i{sqlite3_column_int(stmt,0),(const char*)sqlite3_column_text(stmt,1),(const char*)sqlite3_column_text(stmt,2),(const char*)sqlite3_column_text(stmt,3),(const char*)sqlite3_column_text(stmt,4),sqlite3_column_double(stmt,5)}; sqlite3_finalize(stmt); return i;} sqlite3_finalize(stmt); return std::nullopt; }
std::optional<Instrument> InstrumentRepository::findById(int id){ auto rows=db_.query("SELECT id,symbol,name,type,currency,current_price FROM instruments WHERE id="+std::to_string(id)); if(rows.empty()) return std::nullopt; auto&r=rows[0]; return Instrument{std::stoi(r[0]),r[1],r[2],r[3],r[4],std::stod(r[5])}; }
std::vector<Instrument> InstrumentRepository::list(){ auto rows=db_.query("SELECT id,symbol,name,type,currency,current_price FROM instruments ORDER BY symbol"); std::vector<Instrument> out; for(auto&r:rows) out.push_back({std::stoi(r[0]),r[1],r[2],r[3],r[4],std::stod(r[5])}); return out; }
